management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  #MongoDB configuration
  mongodb:
    host: mongo1
    port: 27017
    database: oomall_demo
  jackson:
    #JSON的时间数据的时区
    time-zone: GMT+8


