management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  #MongoDB configuration
  mongodb:
    host: mongo
    port: 27017
    database: oomall
    username: demouser
    password: '123456'
    authentication-database: oomall
  jackson:
    #JSON的时间数据的时区
    time-zone: GMT+8


